name: Rust Check

on: #[push]
  workflow_call

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v4
      - uses: cargo-bins/cargo-binstall@main
      - name: Update rust
        run: |
          rustup override set stable
          rustup update stable
      - name: Run tests
        run: cargo test
      #- name: Lint
        #run: cargo clippy
      - name: Check formatting
        run: cargo fmt --check
