name: Rust Check

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v4
    - name: Use local
      uses: ./.github/src/hey
    - name: Update rust
      run: |
        rustup override set stable
        rustup update stable
    - name: Run tests
      run: cargo test
    - name: Lint
      run: cargo clippy
    - name: Check formatting
      run: cargo fmt --check
