name: Rust Check

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v4
    - uses: cargo-bins/cargo-binstall@main
    - name: cargo build
      run: cargo build --release
    - name: Update rust
      run: |
        rustup override set stable
        rustup update stable
    - name: Run tests
      run: cargo test
    - name: Lint
      run: cargo clippy
    - name: Check formatting
      run: cargo fmt --check
