name: rust pipeline

# on: 
#   workflow_run:
#     workflows: [Rust check]
#     types: 
#       - completed

# jobs:
#   lint:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - uses: cargo-bins/cargo-binstall@main
#       #- name: Update rust
#         #run: |
#           #rustup override set stable
#           #rustup update stable
#       - name: Lint
#         run: cargo clippy

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    #- uses: ./.github/workflows/myrust.yaml@main
    - uses: rdelsar/github-actions-test/myrust.yaml@main
    - name: lint
      run: cargo clippy
      
