name: rust pipeline

# on: 
#   workflow_run:
#     workflows: [Rust check]
#     types: 
#       - completed

# jobs:
#   lint:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - uses: cargo-bins/cargo-binstall@main
#       #- name: Update rust
#         #run: |
#           #rustup override set stable
#           #rustup update stable
#       - name: Lint
#         run: cargo clippy

on:
  workflow_run:
    workflows: [Rust check]
    types:
      - completed

jobs:
  lint:
    uses: ./.github/workflows/myrust.yaml
  #runs-on: ubuntu-latest
    with:
      #- name: Lint
        run: cargo clippy
      #- name: Lint
        #run: cargo clippy
      
