name: Auto Format Rust Code

on: [pull_request]

permissions:
  contents: write

jobs:
  auto-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event.pull_request.head.ref }}  # Ensure we check out the PR branch

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: Format code
        run: cargo fmt

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "auto format rust code"
          git commit --amend --no-edit
          git push origin HEAD:${{ github.event.pull_request.head.ref }}
# git commit --amend --no-edit
      # - name: Commit changes (single commit only)
      #   run: |
      #     git config --global user.name "github-actions[bot]"
      #     git config --global user.email "github-actions[bot]@users.noreply.github.com"
      #     git add .

      #     git diff --quiet && git diff --staged --quiet || git commit --amend --no-edit

      #     git push --force-with-lease origin HEAD:${{ github.event.pull_request.head.ref }}
